import React, { useRef, useEffect, useState } from "react";
import "../BioGasComponentes/CSS/Index1.css";

const BioEnergySection = () => {
  const bannerRef = useRef(null);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setVisible(true);
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.3 }
    );

    if (bannerRef.current) observer.observe(bannerRef.current);

    return () => observer.disconnect();
  }, []);

  return (
    <section className="bioenergy-section">
      <div className="hero-banner" ref={bannerRef}>
        <div className={`arrow-shapee ${visible ? "animate-arrow" : ""}`}>
          <svg className="arrow-svg" viewBox="0 0 120 180">
            <polygon
              points="0,0 84,0 120,90 84,180 0,180 36,90"
              fill="#f2f2f2"
              stroke="#e3262f"
              strokeWidth="4"
            />
          </svg>
        </div>

        <div className={`hero-text ${visible ? "animate-text" : ""}`}>
          <h1 className="hero-title-outline">Powering</h1>
          <h2 className="hero-title-solid">
            The Future of Agriculture <br /> with Bioenergy
          </h2>
        </div>
      </div>

      <div className="content-wrapper">
        <div className="content-column">
          <p>
            With deep expertise in agricultural production processes,{" "}
            <strong>GD Planet</strong> develops smart and flexible bioenergy
            solutions tailored to every customer's needs. Our goal is to help
            farmers and agri-businesses move toward a cleaner, more efficient,
            and circular energy future.
          </p>

          <p>
            In the agricultural sector, biogas production plays a key role. It
            is generated by breaking down organic materials such as crop
            residues, plant waste, sludge, and animal by-products. This natural
            process fuels <strong>GD's</strong> biogas and biomethane plants —
            turning waste into valuable renewable energy.
          </p>
        </div>

        <div className="content-column">
          <p>
            Napier grass stands out as one of the best raw materials
            (substrates) for biogas and biomethane generation. Biomethane, also
            known as Bio-CNG (Bio-Compressed Natural Gas) or CBG (Compressed
            Biogas), is a clean and sustainable fuel alternative.
          </p>

          <p>
            By investing in biogas plants, farmers and rural entrepreneurs can
            not only meet the growing demand for green energy but also create
            new job opportunities and drive local economic growth — all while
            protecting the planet.
          </p>
        </div>
      </div>
    </section>
  );
};

export default BioEnergySection;
